import { Student, Admin, Room, Notice, ServiceRequest, Payment, HostelRule } from '@/types';

export const dummyStudents: Student[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'student',
    profilePic: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '123-456-7890',
    address: '123 Campus Street, University Town',
    department: 'Computer Science',
    yearOfStudy: 2,
    roomId: '101',
    roomNumber: '101',
    hostelBlock: 'A',
    admissionNumber: 'CS-2021-001',
    paymentStatus: 'paid',
    paymentHistory: [
      {
        id: 'p1',
        studentId: '1',
        amount: 5000,
        date: '2023-01-15',
        dueDate: '2023-01-10',
        status: 'paid',
        type: 'hostel',
        receiptNumber: 'REC-2023-001',
      },
    ],
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'student',
    profilePic: 'https://images.pexels.com/photos/3754438/pexels-photo-3754438.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '234-567-8901',
    address: '456 University Avenue, College City',
    department: 'Electrical Engineering',
    yearOfStudy: 3,
    roomId: '102',
    roomNumber: '102',
    hostelBlock: 'A',
    admissionNumber: 'EE-2020-032',
    paymentStatus: 'pending',
    paymentHistory: [
      {
        id: 'p2',
        studentId: '2',
        amount: 5000,
        date: '2022-12-20',
        dueDate: '2023-01-10',
        status: 'paid',
        type: 'hostel',
        receiptNumber: 'REC-2022-120',
      },
    ],
  },
  {
    id: '3',
    name: 'Michael Johnson',
    email: 'michael.j@example.com',
    role: 'student',
    profilePic: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '345-678-9012',
    address: '789 College Road, Academicville',
    department: 'Mechanical Engineering',
    yearOfStudy: 1,
    roomId: '103',
    roomNumber: '103',
    hostelBlock: 'B',
    admissionNumber: 'ME-2022-045',
    paymentStatus: 'overdue',
    paymentHistory: [
      {
        id: 'p3',
        studentId: '3',
        amount: 5000,
        date: '2022-11-05',
        dueDate: '2022-12-31',
        status: 'overdue',
        type: 'hostel',
      },
    ],
  },
  {
    id: '4',
    name: 'Emily Brown',
    email: 'emily.b@example.com',
    role: 'student',
    profilePic: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '456-789-0123',
    address: '101 Dorm Street, Campus Heights',
    department: 'Chemistry',
    yearOfStudy: 2,
    roomId: '104',
    roomNumber: '104',
    hostelBlock: 'B',
    admissionNumber: 'CH-2021-078',
    paymentStatus: 'paid',
    paymentHistory: [
      {
        id: 'p4',
        studentId: '4',
        amount: 5000,
        date: '2023-01-02',
        dueDate: '2023-01-10',
        status: 'paid',
        type: 'hostel',
        receiptNumber: 'REC-2023-002',
      },
    ],
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david.w@example.com',
    role: 'student',
    profilePic: 'https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '567-890-1234',
    address: '234 Residence Lane, Student City',
    department: 'Physics',
    yearOfStudy: 4,
    roomId: '105',
    roomNumber: '105',
    hostelBlock: 'C',
    admissionNumber: 'PH-2019-120',
    paymentStatus: 'paid',
    paymentHistory: [
      {
        id: 'p5',
        studentId: '5',
        amount: 5000,
        date: '2023-01-08',
        dueDate: '2023-01-10',
        status: 'paid',
        type: 'hostel',
        receiptNumber: 'REC-2023-008',
      },
    ],
  },
];

export const dummyAdmins: Admin[] = [
  {
    id: 'a1',
    name: 'Robert Anderson',
    email: 'robert.a@example.com',
    role: 'admin',
    profilePic: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '123-456-7890',
    position: 'Hostel Warden',
    department: 'Student Affairs',
  },
  {
    id: 'a2',
    name: 'Patricia Thomas',
    email: 'patricia.t@example.com',
    role: 'admin',
    profilePic: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    phone: '234-567-8901',
    position: 'Assistant Warden',
    department: 'Student Affairs',
  },
];

export const dummyRooms: Room[] = [
  {
    id: '101',
    number: '101',
    block: 'A',
    floor: 1,
    capacity: 2,
    occupants: ['1', '2'],
    type: 'double',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan'],
    status: 'full',
  },
  {
    id: '102',
    number: '102',
    block: 'A',
    floor: 1,
    capacity: 1,
    occupants: ['3'],
    type: 'single',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan', 'air conditioner'],
    status: 'full',
  },
  {
    id: '103',
    number: '103',
    block: 'B',
    floor: 1,
    capacity: 2,
    occupants: ['4'],
    type: 'double',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan'],
    status: 'available',
  },
  {
    id: '104',
    number: '104',
    block: 'B',
    floor: 1,
    capacity: 3,
    occupants: ['5'],
    type: 'triple',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan'],
    status: 'available',
  },
  {
    id: '105',
    number: '105',
    block: 'C',
    floor: 1,
    capacity: 1,
    occupants: [],
    type: 'single',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan'],
    status: 'maintenance',
  },
  {
    id: '201',
    number: '201',
    block: 'A',
    floor: 2,
    capacity: 2,
    occupants: [],
    type: 'double',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan'],
    status: 'available',
  },
  {
    id: '202',
    number: '202',
    block: 'A',
    floor: 2,
    capacity: 1,
    occupants: [],
    type: 'single',
    amenities: ['bed', 'desk', 'chair', 'wardrobe', 'fan', 'air conditioner'],
    status: 'available',
  },
];

export const dummyNotices: Notice[] = [
  {
    id: 'n1',
    title: 'Hostel Maintenance Schedule',
    content: 'The hostel will undergo routine maintenance from 10 AM to 2 PM on Saturday, June 15th. Please ensure your rooms are accessible to maintenance staff during this time.',
    date: '2023-06-10',
    author: 'Robert Anderson',
    priority: 'medium',
    tags: ['maintenance', 'schedule'],
  },
  {
    id: 'n2',
    title: 'Upcoming Hostel Fee Deadline',
    content: 'This is a reminder that the hostel fee for the Fall semester is due by July 31st. Please make payments at the accounts office or through the online portal to avoid late fees.',
    date: '2023-06-15',
    author: 'Patricia Thomas',
    priority: 'high',
    tags: ['fees', 'deadline'],
  },
  {
    id: 'n3',
    title: 'New Gym Equipment',
    content: 'We are pleased to inform you that new gym equipment has been installed in the hostel gym. The gym will be open from 6 AM to 10 PM daily.',
    date: '2023-06-20',
    author: 'Robert Anderson',
    priority: 'low',
    tags: ['facilities', 'gym'],
  },
  {
    id: 'n4',
    title: 'Visitor Policy Update',
    content: 'Please note that the visitor policy has been updated. Visitors are now allowed from 9 AM to 7 PM on weekdays and 10 AM to 8 PM on weekends. All visitors must register at the reception.',
    date: '2023-06-25',
    author: 'Patricia Thomas',
    priority: 'medium',
    tags: ['policy', 'visitors'],
  },
  {
    id: 'n5',
    title: 'Internet Maintenance',
    content: 'The hostel Wi-Fi will be under maintenance from 12 AM to 4 AM on Sunday, June 30th. Internet services may be disrupted during this time.',
    date: '2023-06-28',
    author: 'Robert Anderson',
    priority: 'medium',
    tags: ['internet', 'maintenance'],
  },
];

export const dummyServiceRequests: ServiceRequest[] = [
  {
    id: 'sr1',
    title: 'Leaking Faucet',
    description: 'The bathroom faucet is leaking continuously.',
    category: 'plumbing',
    status: 'pending',
    date: '2023-06-01',
    studentId: '1',
    roomId: '101',
    priority: 'medium',
  },
  {
    id: 'sr2',
    title: 'Flickering Light',
    description: 'The light in the study area is flickering and needs to be fixed.',
    category: 'electrical',
    status: 'in-progress',
    date: '2023-06-02',
    studentId: '2',
    roomId: '102',
    priority: 'low',
    assignedTo: 'Maintenance Staff',
  },
  {
    id: 'sr3',
    title: 'Broken Chair',
    description: 'One of the chairs in the room is broken and needs to be replaced.',
    category: 'maintenance',
    status: 'resolved',
    date: '2023-06-03',
    studentId: '3',
    roomId: '103',
    priority: 'low',
    assignedTo: 'Furniture Department',
    comments: [
      {
        id: 'c1',
        userId: 'a1',
        userName: 'Robert Anderson',
        text: 'New chair has been delivered to your room.',
        date: '2023-06-05',
      },
    ],
  },
  {
    id: 'sr4',
    title: 'Air Conditioner Not Working',
    description: 'The AC in my room is not cooling properly.',
    category: 'electrical',
    status: 'pending',
    date: '2023-06-04',
    studentId: '4',
    roomId: '104',
    priority: 'high',
  },
  {
    id: 'sr5',
    title: 'Clogged Drain',
    description: 'The bathroom drain is clogged and water is not draining properly.',
    category: 'plumbing',
    status: 'rejected',
    date: '2023-06-05',
    studentId: '5',
    roomId: '105',
    priority: 'medium',
    comments: [
      {
        id: 'c2',
        userId: 'a2',
        userName: 'Patricia Thomas',
        text: 'This issue was already reported and fixed last week. Please check if it persists and report again if needed.',
        date: '2023-06-06',
      },
    ],
  },
];

export const dummyHostelRules: HostelRule[] = [
  {
    id: 'hr1',
    title: 'Quiet Hours',
    description: 'Quiet hours are from 10 PM to 6 AM. During these hours, please keep noise levels to a minimum to respect the study and sleep needs of fellow residents.',
    category: 'general',
  },
  {
    id: 'hr2',
    title: 'Visitors',
    description: 'Visitors are allowed from 9 AM to 7 PM on weekdays and 10 AM to 8 PM on weekends. All visitors must register at the reception and leave their ID card. Overnight visitors are not allowed without prior permission from the warden.',
    category: 'visitors',
  },
  {
    id: 'hr3',
    title: 'Room Maintenance',
    description: 'Students are responsible for keeping their rooms clean and tidy. Room inspections will be conducted once a month with prior notice. Any damage to hostel property will be charged to the student.',
    category: 'general',
  },
  {
    id: 'hr4',
    title: 'Mess Timings',
    description: 'Breakfast: 7:30 AM - 9:30 AM, Lunch: 12:30 PM - 2:30 PM, Dinner: 7:30 PM - 9:30 PM. Students are expected to follow these timings strictly. Food will not be served outside these hours except in case of medical emergencies.',
    category: 'mess',
  },
  {
    id: 'hr5',
    title: 'Security',
    description: 'Always carry your hostel ID card. Entry to the hostel will not be permitted without it. The main gate will be closed at 10 PM. Late entries require prior permission from the warden.',
    category: 'security',
  },
  {
    id: 'hr6',
    title: 'Electrical Appliances',
    description: 'Usage of electrical appliances like heaters, irons, and kettles is prohibited in rooms due to fire safety concerns. These can be used in designated areas only.',
    category: 'security',
  },
  {
    id: 'hr7',
    title: 'Common Areas',
    description: 'Common areas like TV room, reading room, and gym are for all residents. Please maintain cleanliness and follow the schedules posted for each area.',
    category: 'general',
  },
  {
    id: 'hr8',
    title: 'Internet Usage',
    description: 'Internet facility is provided for academic purposes. Downloading illegal content or excessive bandwidth usage for streaming is prohibited.',
    category: 'general',
  },
];